[variables]
NODE_VERSION = "20.18.1"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build", "ls -la dist"]

[start]
cmd = "npx serve -s dist -p $PORT --single"