[variables]
NODE_VERSION = "20.18.1"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -c serve.json -l tcp://0.0.0.0:$PORT"