[variables]
NODE_VERSION = "20.18.1"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build --workspace=magic-english-frontend", "ls -la frontend/dist", "cp -r frontend/dist ./"]

[start]
cmd = "npx serve -s frontend/dist -p $PORT --single"